require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

# No global use_frameworks! and no global use_modular_headers!
platform :ios, podfile_properties['ios.deploymentTarget'] || '16.0'

prepare_react_native_project!

target 'StayGenie' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"]
  else
    config_command = [
      'npx', 'expo-modules-autolinking', 'react-native-config',
      '--json', '--platform', 'ios'
    ]
  end
  config = use_native_modules!(config_command)

  # ---- Selective modular headers ONLY for pods that need it (from your error) ----
  # These lines don't add Firebase to your project; they just tweak how CocoaPods
  # builds the transitive deps if they are present.
  pod 'GoogleUtilities',          :modular_headers => true
  pod 'FirebaseCore',             :modular_headers => true
  pod 'FirebaseCoreExtension',    :modular_headers => true
  pod 'FirebaseCoreInternal',     :modular_headers => true
  pod 'FirebaseAuthInterop',      :modular_headers => true
  pod 'FirebaseAppCheckInterop',  :modular_headers => true
  pod 'RecaptchaInterop',         :modular_headers => true
  pod 'FirebaseAuth',             :modular_headers => true
  # -------------------------------------------------------------------------------

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'].nil? || podfile_properties['expo.jsEngine'] == 'hermes',
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => (ENV['USE_CCACHE'] == '1' || podfile_properties['apple.ccacheEnabled'] == 'true'),
    )
  end
end
